In [1]:
from kagglehub import KaggleDatasetAdapter
import kagglehub
from dotenv import load_dotenv

# Note the correct file name here
file_path = "disease_prediction.csv"
load_dotenv()

# load_dataset is deprecated, but you can still use it or switch to kagglehub.dataset_load
df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "shyamnadhs/heart-disease-prediction-dataset",
    file_path,
)

# Test it
df.head()

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,1,32,Male,101,235,152,79,28.5,73,No,Yes,Low,Yes,Yes
1,2,31,Male,124,191,134,77,33.9,71,No,Yes,Low,Yes,Yes
2,3,45,Male,57,141,114,71,27.2,79,Yes,Yes,Low,No,No
3,4,75,Female,69,268,120,82,21.5,61,Yes,Yes,Medium,No,Yes
4,5,53,Male,107,163,131,75,23.3,73,Yes,No,Low,Yes,Yes

In [2]:
df.sample(5)

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
643,644,50,Male,100,191,110,81,22.4,73,Yes,No,High,Yes,No
153,154,59,Male,109,252,106,83,23.8,68,No,No,Medium,No,No
888,889,57,Female,61,188,120,84,28.4,87,No,Yes,High,Yes,No
445,446,75,Male,119,220,115,71,22.5,56,Yes,No,High,No,No
974,975,55,Male,91,327,107,72,29.6,70,Yes,Yes,High,No,Yes

In [3]:
df.shape

(1000, 14)

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.describe()

,patient_id,age,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,51.190000,104.163000,210.014000,123.893000,81.032000,26.093000,75.968000
std,288.819436,19.847514,25.076508,39.749111,18.701211,9.969974,4.758282,9.902982
min,1.000000,18.000000,30.000000,89.000000,67.000000,49.000000,16.000000,47.000000
25%,250.750000,33.000000,87.000000,183.000000,111.000000,74.000000,22.900000,70.000000
50%,500.500000,52.500000,105.000000,210.500000,124.000000,81.000000,26.000000,76.000000
75%,750.250000,69.000000,121.000000,235.250000,135.000000,88.000000,29.300000,83.000000
max,1000.000000,85.000000,184.000000,339.000000,195.000000,113.000000,41.500000,114.000000

In [6]:
df.nunique()

patient_id             1000
age                      68
gender                    2
glucose_mg_dl           131
cholesterol_mg_dl       188
systolic_bp              94
diastolic_bp             56
bmi                     206
heart_rate               58
smoking                   2
alcohol_consumption       2
physical_activity         3
family_history            2
disease                   2
dtype: int64

In [7]:
df["disease"].value_counts()

disease
Yes    501
No     499
Name: count, dtype: int64

In [8]:
#make a graph of diease with bmi
import matplotlib.pyplot as plt
x=df["age"]
y=df["heart_rate"]
plt.scatter(x, y,c=df["disease"].map({
    "Yes": "red",
    "No": "blue"
}))
plt.xlabel("Age")
plt.ylabel("BMI")
plt.show()

ModuleNotFoundError: No module named 'matplotlib.backends.registry'

In [ ]:
age = df[(df["age"] >= 55) & (df["age"] <= 80)]

print(age["disease"].value_counts())

#In this dataset, individuals aged 55–80 have a higher proportion of disease cases.

disease
Yes    261
No     144
Name: count, dtype: int64

In [ ]:
df['age']

0      32
1      31
2      45
3      75
4      53
       ..
995    24
996    40
997    44
998    31
999    83
Name: age, Length: 1000, dtype: int64

In [ ]:
df

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,1,32,Male,101,235,152,79,28.5,73,No,Yes,Low,Yes,Yes
1,2,31,Male,124,191,134,77,33.9,71,No,Yes,Low,Yes,Yes
2,3,45,Male,57,141,114,71,27.2,79,Yes,Yes,Low,No,No
3,4,75,Female,69,268,120,82,21.5,61,Yes,Yes,Medium,No,Yes
4,5,53,Male,107,163,131,75,23.3,73,Yes,No,Low,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,24,Male,105,237,86,86,30.9,69,Yes,Yes,Medium,No,No
996,997,40,Male,120,219,133,72,34.3,92,Yes,Yes,Medium,No,No
997,998,44,Female,114,273,114,74,36.0,76,No,No,Low,No,Yes
998,999,31,Male,95,231,130,72,28.2,81,Yes,Yes,Medium,Yes,No
999,1000,83,Male,109,256,103,86,30.3,64,Yes,Yes,High,No,Yes

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import  LogisticRegression
from sklearn.preprocessing import  LabelEncoder

le=LabelEncoder()



x = df[['age', 'heart_rate']]
y=df['disease']


x_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


model = LogisticRegression()
model.fit(x_train,y_train)

model.predict([[53, 70]])

c:\Users\siddi\OneDrive\Desktop\MACHINE LEARNING\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:456: OptimizeWarning: Unknown solver options: iprint
  opt_res = optimize.minimize(
c:\Users\siddi\OneDrive\Desktop\MACHINE LEARNING\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['Yes'], dtype=object)